#!/bin/sh

#Just install/copy config files if they are not exist.
if [ ! -f /etc/my.cnf ]  
then
#install
 echo "INSTALL mysql-atv config file"
 mv /etc/com.atv.mysql.my.cnf /etc/my.cnf

 echo " "
 echo " "
else 
 rm /etc/com.atv.mysql.my.cnf
fi

# Check for a fresh Istallation
if [ ! -d /var/mysql/mysql ]
then
 echo "INSTALL a mysql-atv database"

 # Becaus under iOS 8.3+ the install_db script with 'daemon' permissions 
 # does not have access to the /tmp folder (I don't know why!).
 # So do this with the 'root' user.
 sed -i "s{user                    = daemon{user                    = root{" /etc/my.cnf
 /usr/local/bin/mysql_install_db
 # Change it back to 'daemon' user...
 sed -i "s{user                    = root{user                    = daemon{" /etc/my.cnf
 # ...and change the owner of the folder /var/mysql to 'daemon:wheel'
 chown daemon:wheel /var/mysql -R

 echo "You will find the database files here: /var/mysql"
 echo "You can start the Mysql server with the command below:"
 echo "/usr/local/bin/mysqld_safe &"
 echo "After that you have to set your MySQL root password:"
 echo "/usr/local/bin/mysql_secure_installation" 
 echo " "
 echo " "
else

 #START of bad Taig Group Jailbreak Check
 echo "Checking for an installed mysql-atv on a previous bad Taig Group jailbreak."
 echo "Checking permission of /var/mysql ..."
 #Get user and group permission of /var/mysql
 F_USER="$(stat -c %U /var/mysql)"
 F_GROUP="$(stat -c %G /var/mysql)"
 #Define needed user/group permission of /var/mysql
 N_USER="daemon"
 N_GROUP="wheel"
 #Checking for an installed mysql-atv on a previous bad Taig Group jailbreak
 if [ "$F_GROUP" == "$N_GROUP" ]
 then
  echo "No mysql-atv on a previous bad Taig jailbreak found..."
  echo "Nothing to change. Good!"
 else
  echo "mysql-atv on a previous bad Taig jailbreak found..."
  echo "Change permission of /var/mysql from $F_USER:$F_GROUP to $N_USER:$N_GROUP"
  chown $N_USER:$N_GROUP /var/mysql -R
 fi
 echo "...Done!"
 #END of bad Taig Group Jailbreak Check
fi


 #During a package upgrade, the old packages scripts will stop and don't restart 'mysqld'
 #Therefore we have to restart it again .... just for atv-lighttpd-php-mysql
 if [ -f /Library/LaunchDaemons/com.atv.mysql.plist ]
 then
  launchctl load -w /Library/LaunchDaemons/com.atv.mysql.plist
 fi


exit 0



